import { Mitr } from 'next/font/google'
import { getServerSession } from 'next-auth'
import SessionProvider from './components/SessionProvider'
import './globals.css'

const mitr = Mitr({
  weight: '300',  // Lighter font weight
  subsets: ['latin'],  // Include other subsets if necessary
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={mitr.className}>
          <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  )
}
