import { Mitr } from 'next/font/google'
import { getServerSession } from 'next-auth'

import SessionProvider from './components/SessionProvider'
import './globals.css'

const mitr = Mitr({
  weight: '300',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Professor Portfolio - แฟ้มรวมผลงานอาจารย์',
  description: 'Generated by Professor Portfolio - แฟ้มรวมผลงานอาจารย์',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={mitr.className}>
          <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  )
}
