import { Kodchasan } from 'next/font/google'
import { getServerSession } from 'next-auth'

import SessionProvider from './components/SessionProvider'
import './globals.css'

const kodchasan = Kodchasan({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={kodchasan.className}>
          <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  )
}